<div style="background: linear-gradient(120deg, #1a3a5c 0%, #2d6a9f 60%, #4a9eda 100%); padding: 28px 36px; border-radius: 14px; display: flex; align-items: center; gap: 28px; box-shadow: 0 4px 18px rgba(0,0,0,0.18);">
    <img src='Figures/iteso.jpg' style="height: 110px; border-radius: 8px; background: white; padding: 6px; flex-shrink: 0; box-shadow: 0 2px 8px rgba(0,0,0,0.2);"/>
    <div style="border-left: 2px solid rgba(255,255,255,0.4); padding-left: 28px;">
        <h1 style="margin: 0 0 8px 0; color: white; font-size: 1.5em; line-height: 1.3;">Ingeniería y Ciencia de Datos</h1>
        <h3 style="margin: 0 0 8px 0; color: white; font-size: 1.5em; line-height: 1.3;">Laboratorio de Procesamiento de Datos</h3>
        <h3 style="margin: 0; color: rgba(255,255,255,0.8); font-weight: normal; font-size: 1.05em;">Módulo 1: Extracción de datos de diferentes fuentes: Archivos de Texto</h3>
    </div>
</div>

# Archivos de texto

Los archivos de texto no siempre tienen una estructura explícita. Para extraerlos hay que determinar si sus campos están separados por tabuladores, comas, espacios u otro delimitador, o si cada columna ocupa un ancho fijo.

### De texto a `DataFrame`

La estrategia elegida debe corresponder al formato real. Si el separador cambia entre filas, hay que normalizar la fuente antes de convertirla en tabla; si el archivo contiene texto libre, conviene leerlo como una cadena y aplicar técnicas de procesamiento de lenguaje.

`pd.read_fwf` de pandas se utiliza para leer archivos de texto con columnas de ancho fijo (*fixed-width formatted lines*) y cargarlos en un DataFrame. En este formato, la posición de los caracteres define cada columna, no un separador visible.

Es útil para reportes heredados o archivos generados por sistemas antiguos. Antes de usarlo, confirma que las posiciones de inicio y fin sean consistentes en varias filas.

In [1]:
# Configuración común para ejecutar esta sección de forma independiente
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


dir_base = os.getcwd()
print(dir_base)
ruta = os.path.join(dir_base, 'Data')
print(ruta)

C:\Users\uie70742\OneDrive - ITESO\ITESO\Ingeniería y Ciencia de Datos\Laboratorio_de_Procesamiento_de_Datos_02026\Modulo I
C:\Users\uie70742\OneDrive - ITESO\ITESO\Ingeniería y Ciencia de Datos\Laboratorio_de_Procesamiento_de_Datos_02026\Modulo I\Data

In [2]:
os.chdir(ruta)

In [3]:
for file in os.listdir():
    print(file)

.ipynb_checkpoints
API_SI.POV.DDAY_DS2_en_excel_v2_1930012.xls
archivo_csv.csv
archivo_json.json
archivo_parquet.parquet
archivo_texto.txt
conteo_palabras.csv
csvs_ejemplo
data.json
df_tabla2.csv
ejemplo.html
Extracción.ipynb
housing_prices.csv
IFC-Subscriptions-and-Voting-Power-of-Member-Count.xml
imagen.bmp
imagen_procesada.png
inventario.txt
ITESO_entrance.jpg
json_files
metallica.json
México.min.json
plant_catalog.csv
plant_catalog.xml
productos.csv
productos.parquet
reporte_pobreza.xlsx
Salarios_minimos.csv
shp_files
tabla_1.xml
tabla_2.xml
texto_1.txt
texto_2.txt
texto_3.txt

In [4]:
# Extracción a partir de texto separado por tabular
pd.read_fwf(ruta+'/texto_2.txt',header=None) # No se puede especificar el separador

         0    1   2
0      Ana  1.0  10
1     Beto  1.1  10
2  Alfredo  6.0   9
3  Armando  5.0   9

`read_table` de pandas se utiliza para leer archivos de texto delimitados (por defecto, separados por tabulaciones) y cargarlos en un DataFrame

In [5]:
pd.read_table(ruta+'/texto_2.txt',header=None) # sep='\t'

          0    1   2
0  Ana       1.0  10
1  Beto      1.1  10
2  Alfredo   6.0   9
3  Armando   5.0   9

In [6]:
# Extracción a partir de texto separado por comas
pd.read_table(ruta+'/texto_1.txt',sep=',',header=None)

         0    1   2
0      Ana  1.0  10
1     Beto  1.1  10
2  Alfredo  6.0   9
3  Armando  5.0   9

In [7]:
pd.read_table(ruta+'/texto_1.txt',sep=' ',header=None)

          0     1   2
0      Ana,    1,  10
1     Beto,  1.1,  10
2  Alfredo,    6,   9
3  Armando,    5,   9

In [8]:
pd.read_csv(ruta+'/texto_2.txt',header=None,sep='\t') # sep=','

          0    1   2
0  Ana       1.0  10
1  Beto      1.1  10
2  Alfredo   6.0   9
3  Armando   5.0   9

### Formas de acceder a archivos (modos de apertura)

La función `open(archivo, modo)` recibe un **modo** que define qué operaciones se permiten sobre el archivo:

| Modo | Nombre | Descripción |
|---|---|---|
| `'r'` | read | Solo lectura (por defecto). Da error si el archivo no existe. |
| `'w'` | write | Escritura. **Crea** el archivo o **sobrescribe** su contenido. |
| `'a'` | append | Escritura al final; conserva el contenido existente. |
| `'x'` | exclusive | Crea un archivo nuevo; da error si ya existe. |
| `'r+'` | read/write | Lectura y escritura sin borrar el contenido previo. |
| `'b'` | binary | Modo binario (imágenes, parquet…); se combina, p. ej. `'rb'`. |
| `'t'` | text | Modo texto (por defecto); se combina, p. ej. `'rt'`. |

Conviene indicar la codificación con `encoding='utf-8'` para leer correctamente acentos y caracteres especiales. Los métodos de lectura más comunes son `read()` (todo el contenido como una cadena), `readline()` (una sola línea) y `readlines()` (una lista con todas las líneas).

In [9]:
# Conversión de archivo a variable
file=open(ruta+'/texto_3.txt')     # Abrir...
texto=file.read()
file.close()                      # ...despues cerrar

In [10]:
texto

'En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho tiempo que vivÃ\xada un hidalgo de los de lanza en astillero, adarga antigua, rocÃ³n flaco y galgo corredor. Una olla de algo mÃ¡s vaca que carnero, salpicÃ³n las mÃ¡s noches, duelos y quebrantos los sÃ¡bados, lantejas los viernes, algÃºn palomino de aÃ±adidura los domingos, consumÃ\xadan las tres partes de su hacienda. El resto della concluÃ\xadan sayo de velarte, calzas de velludo para las fiestas, con sus pantuflos de lo mesmo, y los dÃ\xadas de entresemana se honraba con su vellorÃ\xad de lo mÃ¡s fino. TenÃ\xada en su casa una ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza, que asÃ\xad ensillaba el rocÃ\xadn como tomaba la podadera. Frisaba la edad de nuestro hidalgo con los cincuenta aÃ±os; era de complexiÃ³n recia, seco de carnes, enjuto de rostro, gran madrugador y amigo de la caza. Quieren decir que tenÃ\xada el sobrenombre de Quijada, o Quesada, que en esto hay alguna diferencia en los autores que deste caso escriben; aunque por conjeturas verosÃ\xadmiles se deja entender que se llamaba Quijana. Pero esto importa poco a nuestro cuento: basta que en la narraciÃ³n dÃ©l no se salga un punto de la verdad.'

In [11]:
# Si ocurre un error durante la ejecución, la variable file se cierra siempre:
with open(ruta+'/texto_3.txt') as file:
  texto=file.read()

In [12]:
texto

'En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho tiempo que vivÃ\xada un hidalgo de los de lanza en astillero, adarga antigua, rocÃ³n flaco y galgo corredor. Una olla de algo mÃ¡s vaca que carnero, salpicÃ³n las mÃ¡s noches, duelos y quebrantos los sÃ¡bados, lantejas los viernes, algÃºn palomino de aÃ±adidura los domingos, consumÃ\xadan las tres partes de su hacienda. El resto della concluÃ\xadan sayo de velarte, calzas de velludo para las fiestas, con sus pantuflos de lo mesmo, y los dÃ\xadas de entresemana se honraba con su vellorÃ\xad de lo mÃ¡s fino. TenÃ\xada en su casa una ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza, que asÃ\xad ensillaba el rocÃ\xadn como tomaba la podadera. Frisaba la edad de nuestro hidalgo con los cincuenta aÃ±os; era de complexiÃ³n recia, seco de carnes, enjuto de rostro, gran madrugador y amigo de la caza. Quieren decir que tenÃ\xada el sobrenombre de Quijada, o Quesada, que en esto hay alguna diferencia en los autores que deste caso escriben; aunque por conjeturas verosÃ\xadmiles se deja entender que se llamaba Quijana. Pero esto importa poco a nuestro cuento: basta que en la narraciÃ³n dÃ©l no se salga un punto de la verdad.'

In [13]:
# Separamos cada palabra de la variable de texto
texto.split()

['En',
 'un',
 'lugar',
 'de',
 'la',
 'Mancha,',
 'de',
 'cuyo',
 'nombre',
 'no',
 'quiero',
 'acordarme,',
 'no',
 'ha',
 'mucho',
 'tiempo',
 'que',
 'vivÃ\xada',
 'un',
 'hidalgo',
 'de',
 'los',
 'de',
 'lanza',
 'en',
 'astillero,',
 'adarga',
 'antigua,',
 'rocÃ³n',
 'flaco',
 'y',
 'galgo',
 'corredor.',
 'Una',
 'olla',
 'de',
 'algo',
 'mÃ¡s',
 'vaca',
 'que',
 'carnero,',
 'salpicÃ³n',
 'las',
 'mÃ¡s',
 'noches,',
 'duelos',
 'y',
 'quebrantos',
 'los',
 'sÃ¡bados,',
 'lantejas',
 'los',
 'viernes,',
 'algÃºn',
 'palomino',
 'de',
 'aÃ±adidura',
 'los',
 'domingos,',
 'consumÃ\xadan',
 'las',
 'tres',
 'partes',
 'de',
 'su',
 'hacienda.',
 'El',
 'resto',
 'della',
 'concluÃ\xadan',
 'sayo',
 'de',
 'velarte,',
 'calzas',
 'de',
 'velludo',
 'para',
 'las',
 'fiestas,',
 'con',
 'sus',
 'pantuflos',
 'de',
 'lo',
 'mesmo,',
 'y',
 'los',
 'dÃ\xadas',
 'de',
 'entresemana',
 'se',
 'honraba',
 'con',
 'su',
 'vellorÃ\xad',
 'de',
 'lo',
 'mÃ¡s',
 'fino.',
 'TenÃ\xada',
 'en',
 'su',
 'casa',
 'una',
 'ama',
 'que',
 'pasaba',
 'de',
 'los',
 'cuarenta,',
 'y',
 'una',
 'sobrina',
 'que',
 'no',
 'llegaba',
 'a',
 'los',
 'veinte,',
 'y',
 'un',
 'mozo',
 'de',
 'campo',
 'y',
 'plaza,',
 'que',
 'asÃ\xad',
 'ensillaba',
 'el',
 'rocÃ\xadn',
 'como',
 'tomaba',
 'la',
 'podadera.',
 'Frisaba',
 'la',
 'edad',
 'de',
 'nuestro',
 'hidalgo',
 'con',
 'los',
 'cincuenta',
 'aÃ±os;',
 'era',
 'de',
 'complexiÃ³n',
 'recia,',
 'seco',
 'de',
 'carnes,',
 'enjuto',
 'de',
 'rostro,',
 'gran',
 'madrugador',
 'y',
 'amigo',
 'de',
 'la',
 'caza.',
 'Quieren',
 'decir',
 'que',
 'tenÃ\xada',
 'el',
 'sobrenombre',
 'de',
 'Quijada,',
 'o',
 'Quesada,',
 'que',
 'en',
 'esto',
 'hay',
 'alguna',
 'diferencia',
 'en',
 'los',
 'autores',
 'que',
 'deste',
 'caso',
 'escriben;',
 'aunque',
 'por',
 'conjeturas',
 'verosÃ\xadmiles',
 'se',
 'deja',
 'entender',
 'que',
 'se',
 'llamaba',
 'Quijana.',
 'Pero',
 'esto',
 'importa',
 'poco',
 'a',
 'nuestro',
 'cuento:',
 'basta',
 'que',
 'en',
 'la',
 'narraciÃ³n',
 'dÃ©l',
 'no',
 'se',
 'salga',
 'un',
 'punto',
 'de',
 'la',
 'verdad.']

In [14]:
texto.split?

Signature: texto.split(sep=None, maxsplit=-1)
Docstring:
Return a list of the substrings in the string, using sep as the separator string.

  sep
    The separator used to split the string.

    When set to None (the default value), will split on any whitespace
    character (including \\n \\r \\t \\f and spaces) and will discard
    empty strings from the result.
  maxsplit
    Maximum number of splits (starting from the left).
    -1 (the default value) means no limit.

Note, str.split() is mainly useful for data that has been intentionally
delimited.  With natural text that includes punctuation, consider using
the regular expression module.
Type:      builtin_function_or_method

#### Ejemplos de los distintos modos y métodos de lectura/escritura

A continuación se ilustran `readline` y `readlines`, y los modos de escritura (`'w'`) y adición (`'a'`) creando un archivo nuevo en la carpeta `Data`.

In [15]:
ruta

'C:\\Users\\uie70742\\OneDrive - ITESO\\ITESO\\Ingeniería y Ciencia de Datos\\Laboratorio_de_Procesamiento_de_Datos_02026\\Modulo I\\Data'

In [16]:
# read() lee todo; readline() una línea; readlines() una lista de líneas
with open(ruta + '/texto_3.txt', 'r', encoding='utf-8') as f:
    primera_linea = f.readline()

primera_linea

'En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho tiempo que vivía un hidalgo de los de lanza en astillero, adarga antigua, rocón flaco y galgo corredor. Una olla de algo más vaca que carnero, salpicón las más noches, duelos y quebrantos los sábados, lantejas los viernes, algún palomino de añadidura los domingos, consumían las tres partes de su hacienda. El resto della concluían sayo de velarte, calzas de velludo para las fiestas, con sus pantuflos de lo mesmo, y los días de entresemana se honraba con su vellorí de lo más fino. Tenía en su casa una ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza, que así ensillaba el rocín como tomaba la podadera. Frisaba la edad de nuestro hidalgo con los cincuenta años; era de complexión recia, seco de carnes, enjuto de rostro, gran madrugador y amigo de la caza. Quieren decir que tenía el sobrenombre de Quijada, o Quesada, que en esto hay alguna diferencia en los autores que deste caso escriben; aunque por conjeturas verosímiles se deja entender que se llamaba Quijana. Pero esto importa poco a nuestro cuento: basta que en la narración dél no se salga un punto de la verdad.'

In [17]:
nuevo_archivo = os.path.join(ruta, 'inventario.txt')
nuevo_archivo

'C:\\Users\\uie70742\\OneDrive - ITESO\\ITESO\\Ingeniería y Ciencia de Datos\\Laboratorio_de_Procesamiento_de_Datos_02026\\Modulo I\\Data\\inventario.txt'

In [18]:
# Modo 'w': crea (o sobrescribe) un archivo de texto
lista_nueva = ['manzana, 3\n', 'piña, 2\n', 'Pera, 5\n']
with open(nuevo_archivo, 'w', encoding='utf-8') as f:
    f.writelines(lista_nueva)

# Verificamos el contenido escrito
with open(ruta + '/inventario.txt', 'r', encoding='utf-8') as f:
    print(f.read())

manzana, 3
piña, 2
Pera, 5

In [19]:
# Modo 'a': agrega contenido al final sin borrar lo existente
with open(ruta + '/inventario.txt', 'a', encoding='utf-8') as f:
    f.write('naranja,8\n')

with open(ruta + '/inventario.txt', 'r', encoding='utf-8') as f:
    print(f.read())

manzana, 3
piña, 2
Pera, 5
naranja,8

[reading-writing-text-files-python](https://www.geeksforgeeks.org/python/reading-writing-text-files-python/)

### Expresiones regulares

Las **expresiones regulares** (*regex*) describen patrones de texto. Son apropiadas cuando la fuente no tiene una estructura tabular, pero sí reglas repetibles: correos, fechas, identificadores o códigos.

El flujo habitual es: definir el patrón, probarlo con ejemplos representativos, extraer coincidencias y validar los casos que no coincidan. Una regex demasiado general puede capturar datos incorrectos; una demasiado estricta puede omitir variaciones válidas.

Las **expresiones regulares** (regex) son patrones que se utilizan para buscar, extraer o manipular texto de manera flexible y eficiente. Permiten identificar cadenas de texto que cumplen ciertas reglas, como correos electrónicos, números de teléfono, palabras específicas, etc.

##### ¿Cómo se usan en Python?

En Python, se utiliza el módulo `re` para trabajar con expresiones regulares. Algunas funciones comunes son:

- `re.search()`: busca un patrón en cualquier posición y devuelve la primera coincidencia.
- `re.match()`: comprueba la coincidencia desde el inicio de la cadena.
- `re.findall()`: devuelve todas las coincidencias como una lista.
- `re.split()`: divide el texto usando el patrón como separador.
- `re.sub()`: reemplaza coincidencias por otro texto.

##### ¿Cómo definir patrones en regex?

- Los patrones se definen como cadenas de texto; el prefijo `r` evita que Python interprete algunas barras invertidas antes que regex.
- Algunos caracteres especiales:
  - `.`: cualquier carácter excepto salto de línea
  - `\d`: un dígito (0-9)
  - `\w`: un carácter alfanumérico o guion bajo
  - `\s`: un espacio en blanco
  - `*`: cero o más repeticiones
  - `+`: una o más repeticiones
  - `?`: cero o una repetición
  - `^`: inicio de línea
  - `$`: fin de línea
  - `[abc]`: cualquier carácter a, b o c
  - `( )`: agrupación y captura

> **Lectura del ejemplo:** `\w+@\w+\.\w+` busca una estructura simple de correo. Es útil para aprender, pero no pretende validar todas las direcciones permitidas por los estándares de correo.

##### Ejemplo: Correos electrónicos

In [20]:
import re

texto_correo = "Mi correo es gdesirena@iteso.mx pero anteriormente usaba gdesirena@gmail.com"
patron = r"\w+@\w+\.\w+"  # patrón para un correo electrónico

resultado = re.search(patron, texto_correo)
if resultado:
    print("Correo encontrado:", resultado.group())

Correo encontrado: gdesirena@iteso.mx

In [21]:
 #Encuentra todos los correos en texto_correo
re.findall(patron, texto_correo)

['gdesirena@iteso.mx', 'gdesirena@gmail.com']

In [22]:
#captura el dominio después del @
dominios = re.findall(r'@([\w\.-]+)', texto_correo)

In [23]:
dominios

['iteso.mx', 'gmail.com']

In [24]:
texto_fechas = 'algunas fechas importantes son 15/09/2023 y 01/01/2024.' 
fechas = re.findall(r'\b\d{2}/\d{2}/\d{4}\b', texto_fechas)
#Encuentra todas las fechas
fechas

['15/09/2023', '01/01/2024']

##### Ejemplo: Conteo de palabras usando regex

In [25]:
texto

'En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho tiempo que vivÃ\xada un hidalgo de los de lanza en astillero, adarga antigua, rocÃ³n flaco y galgo corredor. Una olla de algo mÃ¡s vaca que carnero, salpicÃ³n las mÃ¡s noches, duelos y quebrantos los sÃ¡bados, lantejas los viernes, algÃºn palomino de aÃ±adidura los domingos, consumÃ\xadan las tres partes de su hacienda. El resto della concluÃ\xadan sayo de velarte, calzas de velludo para las fiestas, con sus pantuflos de lo mesmo, y los dÃ\xadas de entresemana se honraba con su vellorÃ\xad de lo mÃ¡s fino. TenÃ\xada en su casa una ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza, que asÃ\xad ensillaba el rocÃ\xadn como tomaba la podadera. Frisaba la edad de nuestro hidalgo con los cincuenta aÃ±os; era de complexiÃ³n recia, seco de carnes, enjuto de rostro, gran madrugador y amigo de la caza. Quieren decir que tenÃ\xada el sobrenombre de Quijada, o Quesada, que en esto hay alguna diferencia en los autores que deste caso escriben; aunque por conjeturas verosÃ\xadmiles se deja entender que se llamaba Quijana. Pero esto importa poco a nuestro cuento: basta que en la narraciÃ³n dÃ©l no se salga un punto de la verdad.'

In [26]:
#re.split?
L = re.split(r'\W', texto)
L

['En',
 'un',
 'lugar',
 'de',
 'la',
 'Mancha',
 '',
 'de',
 'cuyo',
 'nombre',
 'no',
 'quiero',
 'acordarme',
 '',
 'no',
 'ha',
 'mucho',
 'tiempo',
 'que',
 'vivÃ',
 'a',
 'un',
 'hidalgo',
 'de',
 'los',
 'de',
 'lanza',
 'en',
 'astillero',
 '',
 'adarga',
 'antigua',
 '',
 'rocÃ³n',
 'flaco',
 'y',
 'galgo',
 'corredor',
 '',
 'Una',
 'olla',
 'de',
 'algo',
 'mÃ',
 's',
 'vaca',
 'que',
 'carnero',
 '',
 'salpicÃ³n',
 'las',
 'mÃ',
 's',
 'noches',
 '',
 'duelos',
 'y',
 'quebrantos',
 'los',
 'sÃ',
 'bados',
 '',
 'lantejas',
 'los',
 'viernes',
 '',
 'algÃºn',
 'palomino',
 'de',
 'aÃ',
 'adidura',
 'los',
 'domingos',
 '',
 'consumÃ',
 'an',
 'las',
 'tres',
 'partes',
 'de',
 'su',
 'hacienda',
 '',
 'El',
 'resto',
 'della',
 'concluÃ',
 'an',
 'sayo',
 'de',
 'velarte',
 '',
 'calzas',
 'de',
 'velludo',
 'para',
 'las',
 'fiestas',
 '',
 'con',
 'sus',
 'pantuflos',
 'de',
 'lo',
 'mesmo',
 '',
 'y',
 'los',
 'dÃ',
 'as',
 'de',
 'entresemana',
 'se',
 'honraba',
 'con',
 'su',
 'vellorÃ',
 '',
 'de',
 'lo',
 'mÃ',
 's',
 'fino',
 '',
 'TenÃ',
 'a',
 'en',
 'su',
 'casa',
 'una',
 'ama',
 'que',
 'pasaba',
 'de',
 'los',
 'cuarenta',
 '',
 'y',
 'una',
 'sobrina',
 'que',
 'no',
 'llegaba',
 'a',
 'los',
 'veinte',
 '',
 'y',
 'un',
 'mozo',
 'de',
 'campo',
 'y',
 'plaza',
 '',
 'que',
 'asÃ',
 '',
 'ensillaba',
 'el',
 'rocÃ',
 'n',
 'como',
 'tomaba',
 'la',
 'podadera',
 '',
 'Frisaba',
 'la',
 'edad',
 'de',
 'nuestro',
 'hidalgo',
 'con',
 'los',
 'cincuenta',
 'aÃ',
 'os',
 '',
 'era',
 'de',
 'complexiÃ³n',
 'recia',
 '',
 'seco',
 'de',
 'carnes',
 '',
 'enjuto',
 'de',
 'rostro',
 '',
 'gran',
 'madrugador',
 'y',
 'amigo',
 'de',
 'la',
 'caza',
 '',
 'Quieren',
 'decir',
 'que',
 'tenÃ',
 'a',
 'el',
 'sobrenombre',
 'de',
 'Quijada',
 '',
 'o',
 'Quesada',
 '',
 'que',
 'en',
 'esto',
 'hay',
 'alguna',
 'diferencia',
 'en',
 'los',
 'autores',
 'que',
 'deste',
 'caso',
 'escriben',
 '',
 'aunque',
 'por',
 'conjeturas',
 'verosÃ',
 'miles',
 'se',
 'deja',
 'entender',
 'que',
 'se',
 'llamaba',
 'Quijana',
 '',
 'Pero',
 'esto',
 'importa',
 'poco',
 'a',
 'nuestro',
 'cuento',
 '',
 'basta',
 'que',
 'en',
 'la',
 'narraciÃ³n',
 'dÃ',
 'l',
 'no',
 'se',
 'salga',
 'un',
 'punto',
 'de',
 'la',
 'verdad',
 '']

In [27]:
# Convertimos la lista a set
S = set(L)
S

{'',
 'El',
 'En',
 'Frisaba',
 'Mancha',
 'Pero',
 'Quesada',
 'Quieren',
 'Quijada',
 'Quijana',
 'TenÃ',
 'Una',
 'a',
 'acordarme',
 'adarga',
 'adidura',
 'algo',
 'alguna',
 'algÃºn',
 'ama',
 'amigo',
 'an',
 'antigua',
 'as',
 'astillero',
 'asÃ',
 'aunque',
 'autores',
 'aÃ',
 'bados',
 'basta',
 'calzas',
 'campo',
 'carnero',
 'carnes',
 'casa',
 'caso',
 'caza',
 'cincuenta',
 'como',
 'complexiÃ³n',
 'con',
 'concluÃ',
 'conjeturas',
 'consumÃ',
 'corredor',
 'cuarenta',
 'cuento',
 'cuyo',
 'de',
 'decir',
 'deja',
 'della',
 'deste',
 'diferencia',
 'domingos',
 'duelos',
 'dÃ',
 'edad',
 'el',
 'en',
 'enjuto',
 'ensillaba',
 'entender',
 'entresemana',
 'era',
 'escriben',
 'esto',
 'fiestas',
 'fino',
 'flaco',
 'galgo',
 'gran',
 'ha',
 'hacienda',
 'hay',
 'hidalgo',
 'honraba',
 'importa',
 'l',
 'la',
 'lantejas',
 'lanza',
 'las',
 'llamaba',
 'llegaba',
 'lo',
 'los',
 'lugar',
 'madrugador',
 'mesmo',
 'miles',
 'mozo',
 'mucho',
 'mÃ',
 'n',
 'narraciÃ³n',
 'no',
 'noches',
 'nombre',
 'nuestro',
 'o',
 'olla',
 'os',
 'palomino',
 'pantuflos',
 'para',
 'partes',
 'pasaba',
 'plaza',
 'poco',
 'podadera',
 'por',
 'punto',
 'que',
 'quebrantos',
 'quiero',
 'recia',
 'resto',
 'rocÃ',
 'rocÃ³n',
 'rostro',
 's',
 'salga',
 'salpicÃ³n',
 'sayo',
 'se',
 'seco',
 'sobrenombre',
 'sobrina',
 'su',
 'sus',
 'sÃ',
 'tenÃ',
 'tiempo',
 'tomaba',
 'tres',
 'un',
 'una',
 'vaca',
 'veinte',
 'velarte',
 'vellorÃ',
 'velludo',
 'verdad',
 'verosÃ',
 'viernes',
 'vivÃ',
 'y'}

In [28]:
S.discard('')
S

{'El',
 'En',
 'Frisaba',
 'Mancha',
 'Pero',
 'Quesada',
 'Quieren',
 'Quijada',
 'Quijana',
 'TenÃ',
 'Una',
 'a',
 'acordarme',
 'adarga',
 'adidura',
 'algo',
 'alguna',
 'algÃºn',
 'ama',
 'amigo',
 'an',
 'antigua',
 'as',
 'astillero',
 'asÃ',
 'aunque',
 'autores',
 'aÃ',
 'bados',
 'basta',
 'calzas',
 'campo',
 'carnero',
 'carnes',
 'casa',
 'caso',
 'caza',
 'cincuenta',
 'como',
 'complexiÃ³n',
 'con',
 'concluÃ',
 'conjeturas',
 'consumÃ',
 'corredor',
 'cuarenta',
 'cuento',
 'cuyo',
 'de',
 'decir',
 'deja',
 'della',
 'deste',
 'diferencia',
 'domingos',
 'duelos',
 'dÃ',
 'edad',
 'el',
 'en',
 'enjuto',
 'ensillaba',
 'entender',
 'entresemana',
 'era',
 'escriben',
 'esto',
 'fiestas',
 'fino',
 'flaco',
 'galgo',
 'gran',
 'ha',
 'hacienda',
 'hay',
 'hidalgo',
 'honraba',
 'importa',
 'l',
 'la',
 'lantejas',
 'lanza',
 'las',
 'llamaba',
 'llegaba',
 'lo',
 'los',
 'lugar',
 'madrugador',
 'mesmo',
 'miles',
 'mozo',
 'mucho',
 'mÃ',
 'n',
 'narraciÃ³n',
 'no',
 'noches',
 'nombre',
 'nuestro',
 'o',
 'olla',
 'os',
 'palomino',
 'pantuflos',
 'para',
 'partes',
 'pasaba',
 'plaza',
 'poco',
 'podadera',
 'por',
 'punto',
 'que',
 'quebrantos',
 'quiero',
 'recia',
 'resto',
 'rocÃ',
 'rocÃ³n',
 'rostro',
 's',
 'salga',
 'salpicÃ³n',
 'sayo',
 'se',
 'seco',
 'sobrenombre',
 'sobrina',
 'su',
 'sus',
 'sÃ',
 'tenÃ',
 'tiempo',
 'tomaba',
 'tres',
 'un',
 'una',
 'vaca',
 'veinte',
 'velarte',
 'vellorÃ',
 'velludo',
 'verdad',
 'verosÃ',
 'viernes',
 'vivÃ',
 'y'}

In [29]:
re.findall('en', texto, flags=re.I)

['En',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en',
 'en']

In [30]:
len(re.findall('en', texto, flags=re.I))

21

In [ ]:
# Buscamos las palabras no repetidas del set en la variable de texto para poderlas contar
re.findall?

In [ ]:
# En, en

In [31]:
d = {} # l=[]
for palabra in S:
    d[palabra] = len(re.findall(palabra, texto, flags=re.I))
d

{'Pero': 1,
 'lantejas': 1,
 'ensillaba': 1,
 'antigua': 1,
 'palomino': 1,
 'resto': 1,
 'importa': 1,
 'plaza': 1,
 'a': 131,
 'mÃ': 4,
 'hay': 1,
 'caso': 1,
 'Mancha': 1,
 'deja': 1,
 'sus': 1,
 'noches': 1,
 'Quieren': 1,
 'hacienda': 1,
 'sayo': 1,
 'carnes': 1,
 'partes': 1,
 'algÃºn': 1,
 'como': 1,
 'esto': 3,
 'las': 3,
 'hidalgo': 2,
 'fiestas': 1,
 'por': 2,
 'mucho': 1,
 'pantuflos': 1,
 'su': 5,
 'quiero': 1,
 'llegaba': 1,
 'lanza': 1,
 'pasaba': 1,
 'poco': 1,
 'della': 1,
 'basta': 1,
 'Quesada': 1,
 'los': 11,
 'galgo': 1,
 'concluÃ': 1,
 'as': 14,
 'lo': 15,
 'se': 6,
 'para': 1,
 'viernes': 1,
 'enjuto': 1,
 'verdad': 1,
 'Quijana': 1,
 'velarte': 1,
 'llamaba': 1,
 'os': 17,
 'madrugador': 1,
 'autores': 1,
 'amigo': 1,
 'an': 11,
 'un': 10,
 's': 71,
 'salga': 1,
 'con': 6,
 'punto': 1,
 'rocÃ³n': 1,
 'caza': 1,
 'carnero': 1,
 'narraciÃ³n': 1,
 'tomaba': 1,
 'consumÃ': 1,
 'veinte': 1,
 'honraba': 1,
 'adarga': 1,
 'velludo': 1,
 'sobrina': 1,
 'cincuenta': 1,
 'Una': 4,
 'ha': 4,
 'duelos': 1,
 'flaco': 1,
 'olla': 1,
 'una': 4,
 'vellorÃ': 1,
 'l': 61,
 'tres': 2,
 'El': 8,
 'asÃ': 1,
 'astillero': 1,
 'salpicÃ³n': 1,
 'TenÃ': 2,
 'o': 88,
 'en': 21,
 'sobrenombre': 1,
 'que': 13,
 'conjeturas': 1,
 'cuento': 1,
 'cuyo': 1,
 'domingos': 1,
 'lugar': 1,
 'mesmo': 1,
 'aÃ': 2,
 'el': 8,
 'mozo': 1,
 'calzas': 1,
 'fino': 1,
 'y': 10,
 'vaca': 1,
 'bados': 1,
 'Frisaba': 1,
 'tiempo': 1,
 'tenÃ': 2,
 'alguna': 1,
 'vivÃ': 1,
 'miles': 1,
 'edad': 1,
 'quebrantos': 1,
 'nombre': 2,
 'no': 9,
 'diferencia': 1,
 'de': 27,
 'aunque': 1,
 'podadera': 1,
 'nuestro': 2,
 'algo': 4,
 'cuarenta': 1,
 'deste': 1,
 'seco': 1,
 'gran': 1,
 'recia': 1,
 'escriben': 1,
 'sÃ': 3,
 'dÃ': 2,
 'En': 21,
 'ama': 2,
 'acordarme': 1,
 'campo': 1,
 'casa': 1,
 'rostro': 1,
 'era': 2,
 'adidura': 1,
 'decir': 1,
 'entresemana': 1,
 'la': 18,
 'complexiÃ³n': 1,
 'n': 73,
 'Quijada': 1,
 'corredor': 1,
 'verosÃ': 1,
 'entender': 1,
 'rocÃ': 2}

In [32]:
df = pd.DataFrame(d.items(), columns=['Palabra', 'Frecuencia'])
df

       Palabra  Frecuencia
0         Pero           1
1     lantejas           1
2    ensillaba           1
3      antigua           1
4     palomino           1
..         ...         ...
143    Quijada           1
144   corredor           1
145     verosÃ           1
146   entender           1
147       rocÃ           2

[148 rows x 2 columns]

##### Más ejemplos de expresiones regulares

Los siguientes ejemplos muestran otras funciones y patrones del módulo `re`: búsqueda de números de teléfono, extracción de precios, sustitución de texto (`re.sub`), la diferencia entre `re.match` y `re.search`, y la captura de **grupos**.

In [33]:
# Búsqueda de números de teléfono con distintos separadores
texto_contacto = 'Teléfonos de contacto: 33-1234-5678, 55 8765 4321 y 3312345678.'
telefonos = re.findall(r'\d{2}[\s-]?\d{4}[\s-]?\d{4}', texto_contacto)
print('Teléfonos encontrados:', telefonos)

Teléfonos encontrados: ['33-1234-5678', '55 8765 4321', '3312345678']

In [34]:
# Extraer precios; el grupo entre paréntesis captura solo el número
texto_precios = 'Los precios son $1,250.00, $99.50 y $12,000.99 pesos.'
precios = re.findall(r'\$([\d,]+\.\d{2})', texto_precios)
print('Precios:', precios)

Precios: ['1,250.00', '99.50', '12,000.99']

In [35]:
# re.sub reemplaza coincidencias: aquí ocultamos los dígitos con '#'
oculto = re.sub(r'\d', '#', texto_contacto)
print(oculto)

Teléfonos de contacto: ##-####-####, ## #### #### y ##########.

In [36]:
# re.match solo coincide al inicio de la cadena; re.search busca en cualquier posición
print('match "Tel"     :', re.match(r'Tel', texto_contacto))       # coincide
print('match "contacto":', re.match(r'contacto', texto_contacto))  # None (no está al inicio)
print('search "contacto":', re.search(r'contacto', texto_contacto))  # sí lo encuentra

match "Tel"     : <re.Match object; span=(0, 3), match='Tel'>
match "contacto": None
search "contacto": <re.Match object; span=(13, 21), match='contacto'>

In [37]:
# Grupos con paréntesis para separar día, mes y año de una fecha
texto_fecha = 'La entrega fue el 15/09/2023.'
m = re.search(r'(\d{2})/(\d{2})/(\d{4})', texto_fecha)
if m:
    print('Fecha completa:', m.group(0))
    print('Día:', m.group(1), '| Mes:', m.group(2), '| Año:', m.group(3))

Fecha completa: 15/09/2023
Día: 15 | Mes: 09 | Año: 2023

In [38]:
# Grupos con nombre para extraer varios registros y pasarlos a un DataFrame
registros = 'Ana:23; Luis:31; Marta:45'
coincidencias = re.findall(r'(?P<nombre>\w+):(?P<edad>\d+)', registros)
pd.DataFrame(coincidencias, columns=['nombre', 'edad'])

  nombre edad
0    Ana   23
1   Luis   31
2  Marta   45

https://regex101.com/

### Actividad: Analizador de archivos de texto con regex

1. Construya un analizador que recorra varios archivos `.txt`, extraiga información mediante expresiones regulares y genere un reporte consolidado. Considere los archivos disponibles en `Data`, entre ellos `texto_1.txt`, `texto_2.txt`, `texto_3.txt`, etc...

1. Define una función llamada `analizar_archivo(ruta_archivo)` que reciba la ruta de un archivo `.txt` y devuelva un diccionario con:
   - nombre del archivo;
   - número de líneas;
   - número de palabras;
   - cantidad de números encontrados;
   - cantidad de números decimales;
   - cantidad de palabras que comienzan con vocal.
   
2. Utiliza `with open(..., encoding='utf-8')` para leer cada archivo. Recorre únicamente los archivos que tengan extensión `.txt`. Ordénalos por nombre para que el análisis sea reproducible.

3. Define y aplica los siguientes patrones con el módulo `re`:
   - **Número entero o decimal:** `r'(?<![\w.])-?\d+(?:[.,]\d+)?(?![\w.])'`
   - **Número decimal:** `r'(?<![\w.])-?\d+[.,]\d+(?![\w.])'`
   - **Palabra que comienza con vocal:** `r'\b[aeiouáéíóúü][a-záéíóúüñ]*\b'`, usando `re.IGNORECASE`.
4. Convierte los resultados en un `DataFrame` y muestra una fila por archivo.


5. Conteste las siguientes Preguntas 
    1. ¿Qué archivo contiene más líneas y cuál contiene más palabras?
    2. ¿Cuántos números enteros o decimales se encontraron en total?
    3. ¿Qué archivo contiene más números decimales?
    4. ¿Qué archivo tiene la mayor proporción de palabras que contiene vocales?