<div style="background: linear-gradient(120deg, #1a3a5c 0%, #2d6a9f 60%, #4a9eda 100%); padding: 28px 36px; border-radius: 14px; display: flex; align-items: center; gap: 28px; box-shadow: 0 4px 18px rgba(0,0,0,0.18);">
    <img src='Figures/iteso.jpg' style="height: 110px; border-radius: 8px; background: white; padding: 6px; flex-shrink: 0; box-shadow: 0 2px 8px rgba(0,0,0,0.2);"/>
    <div style="border-left: 2px solid rgba(255,255,255,0.4); padding-left: 28px;">
        <h1 style="margin: 0 0 8px 0; color: white; font-size: 1.5em; line-height: 1.3;">Ingeniería y Ciencia de Datos</h1>
        <h3 style="margin: 0 0 8px 0; color: white; font-size: 1.5em; line-height: 1.3;">Laboratorio de Procesamiento de Datos</h3>
        <h3 style="margin: 0; color: rgba(255,255,255,0.8); font-weight: normal; font-size: 1.05em;">Módulo 1: Extracción de datos de diferentes fuentes: Archivos Parquet</h3>
    </div>
</div>

# Archivos Parquet

**Parquet** es un formato de almacenamiento **columnar** y **binario** diseñado para el análisis de datos a gran escala. A diferencia de un CSV (que guarda los datos por filas y en texto plano), Parquet organiza la información por columnas, lo que ofrece varias ventajas:

- **Compresión eficiente:** al agrupar datos del mismo tipo en cada columna, se comprime mucho mejor y ocupa menos espacio en disco.
- **Lectura selectiva:** permite leer solo las columnas necesarias sin cargar todo el archivo, acelerando las consultas.
- **Conserva los tipos de dato:** guarda el *esquema* (el tipo de cada columna), a diferencia del CSV donde todo es texto.
- **Estándar en Big Data:** es el formato preferido en herramientas como Apache Spark, Hadoop, AWS Athena y en los *data lakes*.

**¿Cuándo se usa?** Al trabajar con grandes volúmenes de datos, en flujos de trabajo analíticos y cuando se busca eficiencia en almacenamiento y velocidad de lectura.

En `pandas` se usa `df.to_parquet()` para escribir y `pd.read_parquet()` para leer. Requiere un motor instalado: `pyarrow` (recomendado) o `fastparquet`.

In [1]:
# Configuración común para ejecutar esta sección de forma independiente
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dir_base = os.getcwd()
print(dir_base)
ruta = os.path.join(dir_base, 'Data')
print(ruta)

C:\Users\uie70742\OneDrive - ITESO\ITESO\Ingeniería y Ciencia de Datos\Laboratorio_de_Procesamiento_de_Datos_02026\Modulo I
C:\Users\uie70742\OneDrive - ITESO\ITESO\Ingeniería y Ciencia de Datos\Laboratorio_de_Procesamiento_de_Datos_02026\Modulo I\Data

In [ ]:
# Parquet requiere un motor de lectura/escritura. Descomenta si es necesario:
# %pip install pyarrow

In [2]:
!pip install pyarrow

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyarrow in c:\programdata\anaconda3\lib\site-packages (21.0.0)

In [3]:
# Creamos un DataFrame de ejemplo y lo guardamos en formato Parquet
df_parquet = pd.DataFrame({
    'producto': ['manzana', 'pera', 'plátano', 'naranja'],
    'precio': [3.5, 5.0, 2.0, 7.5],
    'cantidad': [10, 8, 20, 5]
})
#Guardando en formato parquet

In [5]:
df_parquet.to_parquet(ruta+'/productos.parquet')

In [6]:
# Lectura completa del archivo Parquet
pd.read_parquet(ruta+'/productos.parquet')

  producto  precio  cantidad
0  manzana     3.5        10
1     pera     5.0         8
2  plátano     2.0        20
3  naranja     7.5         5

In [7]:
# Ventaja de Parquet: leer únicamente algunas columnas
pd.read_parquet(ruta+'/productos.parquet', columns=['precio', 'cantidad'])

   precio  cantidad
0     3.5        10
1     5.0         8
2     2.0        20
3     7.5         5

In [8]:
df_p_leidos = pd.read_parquet(ruta+'/productos.parquet')
df_p_leidos

  producto  precio  cantidad
0  manzana     3.5        10
1     pera     5.0         8
2  plátano     2.0        20
3  naranja     7.5         5

In [15]:
# El esquema (tipos) se conserva, y el tamaño en disco suele ser menor que un CSV
print(df_p_leidos.dtypes)
#Crear un csv


#Verificación de tamaño de csv y parquet

producto     object
precio      float64
cantidad      int64
dtype: object

In [10]:
df_parquet.to_csv(ruta+'/productos.csv')

In [14]:
print(os.path.getsize(ruta+'/productos.csv'), 'bytes')

95 bytes



|  | Archivo CSV (Comma-Separated Values) | Archivo Apache Parquet |
| :--- | :--- | :--- |
| **Representación** | Un documento de **texto plano** basado en filas, diseñado para ser leído tanto por humanos como por máquinas. | El estándar de la industria para **Big Data**, un formato binario basado en columnas optimizado para analítica masiva. |
| **Orientación de datos** | **Por filas**. Lee toda la fila completa (registro por registro), incluso si solo necesitas una columna. | **Por columnas**. Lee solo las columnas específicas que necesitas, ignorando el resto. |
| **Legibilidad** | **Alta**. Se puede abrir en el Bloc de notas o Excel sin herramientas especiales. | **Baja**. Al ser un formato binario, requiere software de programación o herramientas de datos para abrirse. |
| **Almacenamiento** | **Inadecuado para archivos grandes**. No tiene compresión nativa y ocupa mucho espacio en disco. | **Altamente eficiente**. Utiliza algoritmos avanzados que reducen drásticamente el espacio en disco. |
| **Metadatos y Tipos** | **No incluye metadatos**. Todo se guarda como texto; el sistema debe adivinar si un dato es número, fecha o texto. | **Esquema estricto**. Almacena de forma nativa los tipos de datos (int, float, boolean, timestamps), evitando errores de interpretación. |

### Práctica de Laboratorio: de múltiples CSV a un dataset Parquet analítico 

Usando los archivos de la carpeta `Data/csvs_ejemplo/`, el estudiante deberá:

1. **Consolidar** todos los CSV en un solo `DataFrame`.
2. Añadir una columna `origen` con el nombre del archivo de procedencia.
3. Guardar como **Parquet particionado por `Ciudad`**.
4. Comparar **tamaño en disco** y **tiempo de lectura** entre CSV y Parquet.
5. Responder:
   - ¿Cuál es el promedio de `Números` por ciudad?
   - ¿Qué ciudad tiene más registros?
   - ¿Cuánto espacio ahorra Parquet frente a CSV?

ruta

In [16]:
ruta

'C:\\Users\\uie70742\\OneDrive - ITESO\\ITESO\\Ingeniería y Ciencia de Datos\\Laboratorio_de_Procesamiento_de_Datos_02026\\Modulo I\\Data'

In [17]:
os.listdir(ruta)

['.ipynb_checkpoints',
 'API_SI.POV.DDAY_DS2_en_excel_v2_1930012.xls',
 'archivo_csv.csv',
 'archivo_json.json',
 'archivo_parquet.parquet',
 'archivo_texto.txt',
 'conteo_palabras.csv',
 'csvs_ejemplo',
 'data.json',
 'df_tabla2.csv',
 'ejemplo.html',
 'Extracción.ipynb',
 'housing_prices.csv',
 'IFC-Subscriptions-and-Voting-Power-of-Member-Count.xml',
 'imagen.bmp',
 'imagen_procesada.png',
 'inventario.txt',
 'ITESO_entrance.jpg',
 'json_files',
 'metallica.json',
 'México.min.json',
 'plant_catalog.csv',
 'plant_catalog.xml',
 'productos.csv',
 'productos.parquet',
 'reporte_pobreza.xlsx',
 'Salarios_minimos.csv',
 'shp_files',
 'tabla_1.xml',
 'tabla_2.xml',
 'texto_1.txt',
 'texto_2.txt',
 'texto_3.txt']

In [25]:
# Pasos 1, 2:  añadir la columna `origen`.**
carpeta_csv = os.path.join(ruta, 'csvs_ejemplo')
# quitar columnas índice

pd.read_csv(os.path.join(carpeta_csv,'archivo_1.csv'))

  Nombre  Números            Ciudad
0    Ana       10       Guadalajara
1   Beto       25         Monterrey
2  Carla       17  Ciudad de México
3  Diego       32            Puebla

In [22]:
os.listdir(carpeta_csv)

['archivo_1.csv',
 'archivo_2.csv',
 'archivo_3.csv',
 'archivo_4.csv',
 'archivo_5.csv']

In [19]:
carpeta_csv

'C:\\Users\\uie70742\\OneDrive - ITESO\\ITESO\\Ingeniería y Ciencia de Datos\\Laboratorio_de_Procesamiento_de_Datos_02026\\Modulo I\\Data\\csv_ejemplo'

In [29]:
for archivo in os.listdir(carpeta_csv):
    df = pd.read_csv(os.path.join(carpeta_csv,archivo))

dfs = [pd.read_csv(os.path.join(carpeta_csv,archivo)) for archivo in os.listdir(carpeta_csv)]
consolidad_df = pd.concat(dfs, axis=0, ignore_index=True)

In [30]:
consolidad_df

      Nombre  Números            Ciudad
0        Ana       10       Guadalajara
1       Beto       25         Monterrey
2      Carla       17  Ciudad de México
3      Diego       32            Puebla
4      Elena        8         Querétaro
5   Fernando       45       Guadalajara
6   Gabriela       21           Tijuana
7       Hugo       13              León
8       Inés       29            Mérida
9      Jorge       37         Monterrey
10     Karla       19            Puebla
11      Luis       26       Guadalajara
12     Marta       14            Toluca
13   Nicolás       41  Ciudad de México
14    Olivia       23            Cancún
15     Pablo        9           Morelia
16   Quetzal       30            Oaxaca
17      Rosa       18          Veracruz
18     Sofía       22       Guadalajara
19     Tomás       16    Aguascalientes
20    Úrsula       34          Saltillo
21    Víctor       27        Hermosillo

In [33]:
dfs = []
for archivo in os.listdir(carpeta_csv):
    df = pd.read_csv(os.path.join(carpeta_csv,archivo))
    df['origen'] = os.path.basename(archivo)
    dfs.append(df)
consolidad_df = pd.concat(dfs, axis=0, ignore_index=True)
consolidad_df

      Nombre  Números            Ciudad         origen
0        Ana       10       Guadalajara  archivo_1.csv
1       Beto       25         Monterrey  archivo_1.csv
2      Carla       17  Ciudad de México  archivo_1.csv
3      Diego       32            Puebla  archivo_1.csv
4      Elena        8         Querétaro  archivo_2.csv
5   Fernando       45       Guadalajara  archivo_2.csv
6   Gabriela       21           Tijuana  archivo_2.csv
7       Hugo       13              León  archivo_2.csv
8       Inés       29            Mérida  archivo_2.csv
9      Jorge       37         Monterrey  archivo_3.csv
10     Karla       19            Puebla  archivo_3.csv
11      Luis       26       Guadalajara  archivo_3.csv
12     Marta       14            Toluca  archivo_4.csv
13   Nicolás       41  Ciudad de México  archivo_4.csv
14    Olivia       23            Cancún  archivo_4.csv
15     Pablo        9           Morelia  archivo_4.csv
16   Quetzal       30            Oaxaca  archivo_4.csv
17      Rosa       18          Veracruz  archivo_4.csv
18     Sofía       22       Guadalajara  archivo_5.csv
19     Tomás       16    Aguascalientes  archivo_5.csv
20    Úrsula       34          Saltillo  archivo_5.csv
21    Víctor       27        Hermosillo  archivo_5.csv

In [36]:
# 3. Dataset Parquet particionado por Ciudad
#destino = os.path.join(carpeta_csv, 'ventas_particionado')
consolidad_df.to_parquet(carpeta_csv, partition_cols=['Ciudad'])

# Estructura de carpetas y archivos generada

# Ventaja: leer solo una partición con un filtro

In [37]:
for root, dirs, files in os.walk(carpeta_csv):
    for f in files:
        print(os.path.relpath(os.path.join(root,f)))

Data\csvs_ejemplo\archivo_1.csv
Data\csvs_ejemplo\archivo_2.csv
Data\csvs_ejemplo\archivo_3.csv
Data\csvs_ejemplo\archivo_4.csv
Data\csvs_ejemplo\archivo_5.csv
Data\csvs_ejemplo\ventas_particionado
Data\csvs_ejemplo\Ciudad=Aguascalientes\d6126a35a97f460c831a7df1015ab718-0.parquet
Data\csvs_ejemplo\Ciudad=Canc%C3%BAn\d6126a35a97f460c831a7df1015ab718-0.parquet
Data\csvs_ejemplo\Ciudad=Ciudad%20de%20M%C3%A9xico\d6126a35a97f460c831a7df1015ab718-0.parquet
Data\csvs_ejemplo\Ciudad=Guadalajara\d6126a35a97f460c831a7df1015ab718-0.parquet
Data\csvs_ejemplo\Ciudad=Hermosillo\d6126a35a97f460c831a7df1015ab718-0.parquet
Data\csvs_ejemplo\Ciudad=Le%C3%B3n\d6126a35a97f460c831a7df1015ab718-0.parquet
Data\csvs_ejemplo\Ciudad=M%C3%A9rida\d6126a35a97f460c831a7df1015ab718-0.parquet
Data\csvs_ejemplo\Ciudad=Monterrey\d6126a35a97f460c831a7df1015ab718-0.parquet
Data\csvs_ejemplo\Ciudad=Morelia\d6126a35a97f460c831a7df1015ab718-0.parquet
Data\csvs_ejemplo\Ciudad=Oaxaca\d6126a35a97f460c831a7df1015ab718-0.parquet
Data\csvs_ejemplo\Ciudad=Puebla\d6126a35a97f460c831a7df1015ab718-0.parquet
Data\csvs_ejemplo\Ciudad=Quer%C3%A9taro\d6126a35a97f460c831a7df1015ab718-0.parquet
Data\csvs_ejemplo\Ciudad=Saltillo\d6126a35a97f460c831a7df1015ab718-0.parquet
Data\csvs_ejemplo\Ciudad=Tijuana\d6126a35a97f460c831a7df1015ab718-0.parquet
Data\csvs_ejemplo\Ciudad=Toluca\d6126a35a97f460c831a7df1015ab718-0.parquet
Data\csvs_ejemplo\Ciudad=Veracruz\d6126a35a97f460c831a7df1015ab718-0.parquet

In [ ]:
# 4. Comparar tamaño en disco y tiempo de lectura entre CSV y Parquet.
consolidad_df.to_csv('archivo_total.csv')
consolidad_df.to_parquet('archivo_total.parquet')
# Guardamos un único CSV y un único Parquet para comparar

In [ ]:
# 5. Respuestas de análisis
import time