<div style="background: linear-gradient(120deg, #1a3a5c 0%, #2d6a9f 60%, #4a9eda 100%); padding: 28px 36px; border-radius: 14px; display: flex; align-items: center; gap: 28px; box-shadow: 0 4px 18px rgba(0,0,0,0.18);">
    <img src='Figures/iteso.jpg' style="height: 110px; border-radius: 8px; background: white; padding: 6px; flex-shrink: 0; box-shadow: 0 2px 8px rgba(0,0,0,0.2);"/>
    <div style="border-left: 2px solid rgba(255,255,255,0.4); padding-left: 28px;">
        <h1 style="margin: 0 0 8px 0; color: white; font-size: 1.5em; line-height: 1.3;">Ingeniería y Ciencia de Datos</h1>
        <h3 style="margin: 0 0 8px 0; color: white; font-size: 1.5em; line-height: 1.3;">Laboratorio de Procesamiento de Datos</h3>
        <h3 style="margin: 0; color: rgba(255,255,255,0.8); font-weight: normal; font-size: 1.05em;">Módulo 1: Extracción de datos de diferentes fuentes: Archivos JSON</h3>
    </div>
</div>

# Archivos JSON

JSON representa datos mediante pares `clave: valor`, listas y objetos anidados. Es muy habitual en APIs, configuraciones y registros de aplicaciones porque conserva mejor la estructura que una tabla plana.

El proceso tiene dos etapas: `json.load` o `json.loads` convierte el contenido a diccionarios y listas de Python; después, `json_normalize` ayuda a convertir objetos repetidos o anidados en columnas de un DataFrame. No todos los JSON tienen la misma forma, por lo que primero conviene inspeccionar sus claves y niveles.

El formato JSON (JavaScript Object Notation) es ampliamente utilizado para el intercambio de datos, especialmente en aplicaciones web y APIs. Python incluye la librería estándar `json` para leer y manipular archivos JSON.

#### Anatomía de un archivo JSON

JSON se construye con solo dos estructuras que se combinan y anidan, lo que le permite representar datos muy complejos:

- **Objetos** `{ }` → pares `clave: valor` (equivalen a un `dict` de Python).
- **Arreglos** `[ ]` → listas ordenadas de valores (equivalen a una `list`).

| JSON | Python |
|---|---|
| `{ }` *object* | `dict` |
| `[ ]` *array* | `list` |
| `"texto"` | `str` |
| `12`, `3.14` | `int`, `float` |
| `true` / `false` | `True` / `False` |
| `null` | `None` |

El archivo `data.json` es un **catálogo de productos** real: cada elemento tiene nombre, precio (`mrp`), código de barras y una **lista anidada** de `categories`.

```mermaid
flowchart TD
    R["&#123; &#125; raíz"] --> D["data [ ]"]
    D --> P1["&#123; &#125; producto"]
    P1 --> N["itemName, mrp, barcode..."]
    P1 --> C["categories [ ]"]
    C --> CAT["&#123; &#125; objectId, className"]
```

In [1]:
# Configuración común para ejecutar esta sección de forma independiente
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dir_base = os.getcwd()
print(dir_base)
ruta = os.path.join(dir_base, 'Data')
print(ruta)

C:\Users\uie70742\OneDrive - ITESO\ITESO\Ingeniería y Ciencia de Datos\Laboratorio_de_Procesamiento_de_Datos_02026\Modulo I
C:\Users\uie70742\OneDrive - ITESO\ITESO\Ingeniería y Ciencia de Datos\Laboratorio_de_Procesamiento_de_Datos_02026\Modulo I\Data

In [2]:
import json

json_data = '{"personas": [{"nombre": "Ana", "edad": 23}, {"nombre": "Luis", "edad": 31}]}'
data = json.loads(json_data)
print('Personas extraídas del archivo JSON:')
for persona in data['personas']:
    print(f'Nombre: {persona["nombre"]}, Edad: {persona["edad"]}')

Personas extraídas del archivo JSON:
Nombre: Ana, Edad: 23
Nombre: Luis, Edad: 31

In [3]:
#json normalize, cargar un archivo json 
from pandas import json_normalize

with open(os.path.join(ruta, 'data.json')) as jsonfile:
    jsondata = json.load(jsonfile)
jsondata

{'data': [{'_id': 'OzE5vaa3p7',
   'categories': [{'__type': 'Pointer',
     'className': 'Category',
     'objectId': 'nebCwWd2Fr'}],
   'isActive': True,
   'imageUrl': 'https://firebasestorage.googleapis.com/v0/b/shopgro-1376.appspot.com/o/Barcode%20Data%20Upload%28II%29%2FAnil_puttu_flour_500g.png?alt=media&token=9cf63197-0925-4360-a31a-4675f4f46ae2',
   'barcode': '8908001921015',
   'isFmcg': True,
   'itemName': 'Anil puttu flour 500g',
   'mrp': 58,
   '_created_at': '2016-10-02T13:49:03.281Z',
   '_updated_at': '2017-02-22T08:48:09.548Z'},
  {'_id': 'ENPCL8ph1p',
   'categories': [{'__type': 'Pointer',
     'className': 'Category',
     'objectId': 'B4nZeUHmVK'}],
   'isActive': True,
   'imageUrl': 'https://firebasestorage.googleapis.com/v0/b/kirananearby-9eaa8.appspot.com/o/Barcode%20data%20upload%2FYippee_Magic_Masala_Noodles,_70_g.png?alt=media&token=d9e47bd7-f847-4d6f-9460-4be8dbcaae00',
   'barcode': '8901725181222',
   'isFmcg': True,
   'itemName': 'Yippee Magic Masala Noodles, 70 G',
   'mrp': 12,
   '_created_at': '2016-10-02T13:49:03.284Z',
   '_updated_at': '2017-02-22T08:48:09.074Z'}]}

In [4]:
df_json = json_normalize(jsondata['data'])
df_json

,_id,categories,isActive,imageUrl,barcode,isFmcg,itemName,mrp,_created_at,_updated_at
0,OzE5vaa3p7,"[{'__type': 'Pointer', 'className': 'Category'...",True,https://firebasestorage.googleapis.com/v0/b/sh...,8908001921015,True,Anil puttu flour 500g,58,2016-10-02T13:49:03.281Z,2017-02-22T08:48:09.548Z
1,ENPCL8ph1p,"[{'__type': 'Pointer', 'className': 'Category'...",True,https://firebasestorage.googleapis.com/v0/b/ki...,8901725181222,True,"Yippee Magic Masala Noodles, 70 G",12,2016-10-02T13:49:03.284Z,2017-02-22T08:48:09.074Z

In [6]:
# Inspeccionar la estructura antes de normalizar (paso clave con JSON desconocido)
df_json['categories'][0]

[{'__type': 'Pointer', 'className': 'Category', 'objectId': 'nebCwWd2Fr'}]

#### Aplanar estructuras anidadas con `record_path` y `meta`

La columna `categories` es una **lista de objetos** dentro de cada producto. Con `record_path` le indicamos a `json_normalize` cuál es la lista que queremos "explotar" (una fila por categoría), y con `meta` qué campos del nivel superior conservar en cada fila.

In [7]:
# Explotar la lista anidada 'categories' conservando datos del producto
df_cat = json_normalize(
    jsondata['data'],
    record_path='categories',
    meta=['itemName', 'barcode', 'mrp']
)
df_cat

,__type,className,objectId,itemName,barcode,mrp
0,Pointer,Category,nebCwWd2Fr,Anil puttu flour 500g,8908001921015,58
1,Pointer,Category,B4nZeUHmVK,"Yippee Magic Masala Noodles, 70 G",8901725181222,12

#### Un mini análisis sobre el catálogo

Una vez que el JSON es un `DataFrame`, se analiza como cualquier tabla: estadísticas, ordenamientos y filtros.

In [8]:
# Estadística y ordenamiento sobre los datos ya tabulares
df_cat['mrp'].mean()

np.float64(35.0)

In [9]:
df_json[['itemName', 'mrp']].sort_values('mrp', ascending=False)

                            itemName  mrp
0              Anil puttu flour 500g   58
1  Yippee Magic Masala Noodles, 70 G   12

#### Del DataFrame de vuelta a JSON (serialización)

Extraer no es el único camino: también se **serializa** (guardar de Python a JSON). `json.dumps` convierte un objeto de Python a texto JSON, y `DataFrame.to_json` exporta una tabla completa. El argumento `indent` produce una salida legible y `ensure_ascii=False` / `force_ascii=False` conserva los acentos.

In [10]:
# json.dumps: de un dict/list de Python a texto JSON con formato legible
resumen = {'tota_productos': len(jsondata['data']), 'productos': [p['itemName'] for p in jsondata['data']]}
resumen

{'tota_productos': 2,
 'productos': ['Anil puttu flour 500g', 'Yippee Magic Masala Noodles, 70 G']}

In [14]:
print(json.dumps(resumen, indent=2, ensure_ascii=True))

{
  "tota_productos": 2,
  "productos": [
    "Anil puttu flour 500g",
    "Yippee Magic Masala Noodles, 70 G"
  ]
}

In [15]:
# DataFrame.to_json exporta una tabla; orient='records' = lista de objetos
df_json

,_id,categories,isActive,imageUrl,barcode,isFmcg,itemName,mrp,_created_at,_updated_at
0,OzE5vaa3p7,"[{'__type': 'Pointer', 'className': 'Category'...",True,https://firebasestorage.googleapis.com/v0/b/sh...,8908001921015,True,Anil puttu flour 500g,58,2016-10-02T13:49:03.281Z,2017-02-22T08:48:09.548Z
1,ENPCL8ph1p,"[{'__type': 'Pointer', 'className': 'Category'...",True,https://firebasestorage.googleapis.com/v0/b/ki...,8901725181222,True,"Yippee Magic Masala Noodles, 70 G",12,2016-10-02T13:49:03.284Z,2017-02-22T08:48:09.074Z

In [16]:
df_json[['itemName', 'mrp']].to_json(orient='records', indent=2, force_ascii=True)

'[\n  {\n    "itemName":"Anil puttu flour 500g",\n    "mrp":58\n  },\n  {\n    "itemName":"Yippee Magic Masala Noodles, 70 G",\n    "mrp":12\n  }\n]'

#### Atajo: `pd.read_json`

Cuando el JSON ya es una **lista de objetos "plana"** (sin anidamiento), `pd.read_json` crea el `DataFrame` en un solo paso. Es el equivalente de `pd.read_csv`, pero para JSON.

In [ ]:
# pd.read_json convierte una lista de objetos JSON en un DataFrame directamente
json_plano = '[{"ciudad": "Guadalajara", "temp": 28}, {"ciudad": "Monterrey", "temp": 34}]'
pd.read_json(json_plano)

## Práctica de Laboratorio: Extracción de archivos JSON

Utilizando el fichero metallica.json de de los discos del grupo Metallica, crea distintas funciones en python, utilizando la librería json, que realicen las siguientes funciones:

1. **Listar información:** Listar el título del disco, y el contenido y fecha en el que se ha publicado en la wiki.
2. **Contar información:** Mostrar los títulos de discos y el número de canciones que tiene cada una.
3. **Buscar o filtrar información:** Recibe un límite inferior y otro superior, y muestra el título, y los nombres de las etiquetas ("tags") de los discos cuyos número de oyentes esté entre los dos límites.
4. **Buscar información relacionada:** Recibe el nombre una canción y muestra el título del disco donde está.

In [20]:
json_metalica_path = os.path.join(ruta, "metallica.json")
json_metalica_path

'C:\\Users\\uie70742\\OneDrive - ITESO\\ITESO\\Ingeniería y Ciencia de Datos\\Laboratorio_de_Procesamiento_de_Datos_02026\\Modulo I\\Data\\metallica.json'

In [22]:
with open(json_metalica_path, encoding='utf-8') as json_metalica:
    jsondata_metalica = json.load(json_metalica)
jsondata_metalica

[{'album': {'name': "Kill 'Em All",
   'artist': 'Metallica',
   'mbid': 'c06ed440-f25d-3127-aadb-ebe9c685b3d8',
   'url': 'https://www.last.fm/music/Metallica/Kill+%27Em+All',
   'image': [{'#text': 'https://lastfm-img2.akamaized.net/i/u/34s/0e79f0c8fbf341178601367a4a12a890.png',
     'size': 'small'},
    {'#text': 'https://lastfm-img2.akamaized.net/i/u/64s/0e79f0c8fbf341178601367a4a12a890.png',
     'size': 'medium'},
    {'#text': 'https://lastfm-img2.akamaized.net/i/u/174s/0e79f0c8fbf341178601367a4a12a890.png',
     'size': 'large'},
    {'#text': 'https://lastfm-img2.akamaized.net/i/u/300x300/0e79f0c8fbf341178601367a4a12a890.png',
     'size': 'extralarge'},
    {'#text': 'https://lastfm-img2.akamaized.net/i/u/0e79f0c8fbf341178601367a4a12a890.png',
     'size': 'mega'},
    {'#text': 'https://lastfm-img2.akamaized.net/i/u/arQ/0e79f0c8fbf341178601367a4a12a890.png',
     'size': ''}],
   'listeners': '554430',
   'playcount': '13043742',
   'tracks': {'track': [{'name': 'Hit the Lights',
      'url': 'https://www.last.fm/music/Metallica/_/Hit+the+Lights',
      'duration': '257',
      '@attr': {'rank': '1'},
      'streamable': {'#text': '0', 'playcount': '1407956'},
      'artist': {'name': 'Metallica',
       'mbid': '65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab',
       'url': 'https://www.last.fm/music/Metallica'}},
     {'name': 'The Four Horsemen',
      'url': 'https://www.last.fm/music/Metallica/_/The+Four+Horsemen',
      'duration': '428',
      '@attr': {'rank': '2'},
      'streamable': {'#text': '0', 'playcount': '549997'},
      'artist': {'name': 'Metallica',
       'mbid': '65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab',
       'url': 'https://www.last.fm/music/Metallica'}},
     {'name': 'Motorbreath',
      'url': 'https://www.last.fm/music/Metallica/_/Motorbreath',
      'duration': '183',
      '@attr': {'rank': '3'},
      'streamable': {'#text': '0', 'playcount': '1886604'},
      'artist': {'name': 'Metallica',
       'mbid': '65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab',
       'url': 'https://www.last.fm/music/Metallica'}},
     {'name': 'Jump in the Fire',
      'url': 'https://www.last.fm/music/Metallica/_/Jump+in+the+Fire',
      'duration': '290',
      '@attr': {'rank': '4'},
      'streamable': {'#text': '0', 'playcount': '1968887'},
      'artist': {'name': 'Metallica',
       'mbid': '65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab',
       'url': 'https://www.last.fm/music/Metallica'}},
     {'name': '(Anesthesia) Pulling Teeth',
      'url': 'https://www.last.fm/music/Metallica/_/(Anesthesia)+Pulling+Teeth',
      'duration': '207',
      '@attr': {'rank': '5'},
      'streamable': {'#text': '0', 'playcount': '1485446'},
      'artist': {'name': 'Metallica',
       'mbid': '65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab',
       'url': 'https://www.last.fm/music/Metallica'}},
     {'name': 'Whiplash',
      'url': 'https://www.last.fm/music/Metallica/_/Whiplash',
      'duration': '246',
      '@attr': {'rank': '6'},
      'streamable': {'#text': '0', 'playcount': '1858621'},
      'artist': {'name': 'Metallica',
       'mbid': '65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab',
       'url': 'https://www.last.fm/music/Metallica'}},
     {'name': 'Phantom Lord',
      'url': 'https://www.last.fm/music/Metallica/_/Phantom+Lord',
      'duration': '292',
      '@attr': {'rank': '7'},
      'streamable': {'#text': '0', 'playcount': '469152'},
      'artist': {'name': 'Metallica',
       'mbid': '65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab',
       'url': 'https://www.last.fm/music/Metallica'}},
     {'name': 'No Remorse',
      'url': 'https://www.last.fm/music/Metallica/_/No+Remorse',
      'duration': '384',
      '@attr': {'rank': '8'},
      'streamable': {'#text': '0', 'playcount': '1225388'},
      'artist': {'name': 'Metallica',
       'mbid': '65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab',
       'url': 'https://www.last.fm/music/Metallica'}},
     {'name': 'Seek & Destroy',
      'url': 'https://www.last.fm/music/Metallica/_/Seek+&+Destroy',
      'duration': '784',
      '@attr': {'rank': '9'},
      'streamable': {'#text': '0', 'playcount': '1578264'},
      'artist': {'name': 'Metallica',
       'mbid': '65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab',
       'url': 'https://www.last.fm/music/Metallica'}},
     {'name': 'Metal Militia',
      'url': 'https://www.last.fm/music/Metallica/_/Metal+Militia',
      'duration': '366',
      '@attr': {'rank': '10'},
      'streamable': {'#text': '0', 'playcount': '886958'},
      'artist': {'name': 'Metallica',
       'mbid': '65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab',
       'url': 'https://www.last.fm/music/Metallica'}}]},
   'tags': {'tag': [{'name': 'thrash metal',
      'url': 'https://www.last.fm/tag/thrash+metal'},
     {'name': 'albums I own', 'url': 'https://www.last.fm/tag/albums+I+own'},
     {'name': 'metal', 'url': 'https://www.last.fm/tag/metal'},
     {'name': 'heavy metal', 'url': 'https://www.last.fm/tag/heavy+metal'},
     {'name': 'speed metal', 'url': 'https://www.last.fm/tag/speed+metal'}]},
   'wiki': {'published': '01 Apr 2009, 22:18',
    'summary': 'Kill \'Em All is Metallica\'s first studio album. Some of the songs were written by a different line-up than the musicians that played the songs in the studio. It was recorded at Music America Studios, Rochester, New York. It was released by Megaforce on July 29, 1983 and later re-released by Elektra records.\n\nBefore Kill \'Em All was recorded, the songs were written and recorded as demos by James Hetfield, Lloyd Grant, Ron McGovney and Lars Ulrich. On later demos <a href="http://www.last.fm/music/Metallica/Kill+%27Em+All">Read more on Last.fm</a>.',
    'content': 'Kill \'Em All is Metallica\'s first studio album. Some of the songs were written by a different line-up than the musicians that played the songs in the studio. It was recorded at Music America Studios, Rochester, New York. It was released by Megaforce on July 29, 1983 and later re-released by Elektra records.\n\nBefore Kill \'Em All was recorded, the songs were written and recorded as demos by James Hetfield, Lloyd Grant, Ron McGovney and Lars Ulrich. On later demos, featuring the first full tracks that would appear on Kill \'Em All, Dave Mustaine took Lloyd\'s place and Ron was replaced by Cliff Burton. Mustaine was kicked from the band for having a bad attitude and was replaced by the final Metallica lead guitarist Kirk Hammett. With this final line-up Kill \'Em All was recorded.\n\nThe album features a lot of Metallica\'s remarkable thrash songs such as: Seek & Destroy, Whiplash and The Four Horsemen. Unlike the later albums, Kill \'Em All didn\'t have any symphonic sounds or instruments supporting the tracks.\n\nThe original title of the album was supposed to be Metal Up Your Ass and it had a different cover artwork (hand with a dagger sticking out from WC). Megaforce permissed it. The title Kill \'Em All was what Cliff Burton said after the record company rejected the original Metal Up Your Ass cover. "Just fuckin\' kill \'em all" were his exact words. \n <a href="http://www.last.fm/music/Metallica/Kill+%27Em+All">Read more on Last.fm</a>. User-contributed text is available under the Creative Commons By-SA License; additional terms may apply.'}}},
 {'album': {'name': 'Ride the Lightning',
   'artist': 'Metallica',
   'mbid': '2236dd07-a2f3-466a-973d-9069001a89da',
   'url': 'https://www.last.fm/music/Metallica/Ride+the+Lightning',
   'image': [{'#text': 'https://lastfm-img2.akamaized.net/i/u/34s/dfe9c2366530411396c881090c2039d2.png',
     'size': 'small'},
    {'#text': 'https://lastfm-img2.akamaized.net/i/u/64s/dfe9c2366530411396c881090c2039d2.png',
     'size': 'medium'},
    {'#text': 'https://lastfm-img2.akamaized.net/i/u/174s/dfe9c2366530411396c881090c2039d2.png',
     'size': 'large'},
    {'#text': 'https://lastfm-img2.akamaized.net/i/u/300x300/dfe9c2366530411396c881090c2039d2.png',
     'size': 'extralarge'},
    {'#text': 'https://lastfm-img2.akamaized.net/i/u/dfe9c2366530411396c881090c2039d2.png',
     'size': 'mega'},
    {'#text': 'https://lastfm-img2.akamaized.net/i/u/arQ/dfe9c2366530411396c881090c2039d2.png',
     'size': ''}],
   'listeners': '761909',
   'playcount': '17549813',
   'tracks': {'track': [{'name': 'Fight Fire With Fire',
      'url': 'https://www.last.fm/music/Metallica/_/Fight+Fire+With+Fire',
      'duration': '284',
      '@attr': {'rank': '1'},
      'streamable': {'#text': '0', 'playcount': '1939620'},
      'artist': {'name': 'Metallica',
       'mbid': '65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab',
       'url': 'https://www.last.fm/music/Metallica'}},
     {'name': 'Ride the Lightning',
      'url': 'https://www.last.fm/music/Metallica/_/Ride+the+Lightning',
      'duration': '396',
      '@attr': {'rank': '2'},
      'streamable': {'#text': '0', 'playcount': '884894'},
      'artist': {'name': 'Metallica',
       'mbid': '65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab',
       'url': 'https://www.last.fm/music/Metallica'}},
     {'name': 'For Whom the Bell Tolls',
      'url': 'https://www.last.fm/music/Metallica/_/For+Whom+the+Bell+Tolls',
      'duration': '310',
      '@attr': {'rank': '3'},
      'streamable': {'#text': '0', 'playcount': '420744'},
      'artist': {'name': 'Metallica',
       'mbid': '65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab',
       'url': 'https://www.last.fm/music/Metallica'}},
     {'name': 'Fade to Black',
      'url': 'https://www.last.fm/music/Metallica/_/Fade+to+Black',
      'duration': '416',
      '@attr': {'rank': '4'},
      'streamable': {'#text': '0', 'playcount': '778461'},
      'artist': {'name': 'Metallica',
       'mbid': '65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab',
       'url': 'https://www.last.fm/music/Metallica'}},
     {'name': 'Trapped Under Ice',
      'url': 'https://www.last.fm/music/Metallica/_/Trapped+Under+Ice',
      'duration': '243',
      '@attr': {'rank': '5'},
      'streamable': {'#text': '0', 'playcount': '427242'},
      'artist': {'name': 'Metallica',
       'mbid': '65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab',
       'url': 'https://www.last.fm/music/Metallica'}},
     {'name': 'Escape',
      'url': 'https://www.last.fm/music/Metallica/_/Escape',
      'duration': '263',
      '@attr': {'rank': '6'},
      'streamable': {'#text': '0', 'playcount': '419203'},
      'artist': {'name': 'Metallica',
       'mbid': '65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab',
       'url': 'https://www.last.fm/music/Metallica'}},
     {'name': 'Creeping Death',
      'url': 'https://www.last.fm/music/Metallica/_/Creeping+Death',
      'duration': '396',
      '@attr': {'rank': '7'},
      'streamable': {'#text': '0', 'playcount': '1531300'},
      'artist': {'name': 'Metallica',
       'mbid': '65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab',
       'url': 'https://www.last.fm/music/Metallica'}},
     {'name': 'The Call of Ktulu',
      'url': 'https://www.last.fm/music/Metallica/_/The+Call+of+Ktulu',
      'duration': '532',
      '@attr': {'rank': '8'},
      'streamable': {'#text': '0', 'playcount': '1622954'},
      'artist': {'name': 'Metallica',
       'mbid': '65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab',
       'url': 'https://www.last.fm/music/Metallica'}}]},
   'tags': {'tag': [{'name': 'thrash metal',
      'url': 'https://www.last.fm/tag/thrash+metal'},
     {'name': 'albums I own', 'url': 'https://www.last.fm/tag/albums+I+own'},
     {'name': 'metal', 'url': 'https://www.last.fm/tag/metal'},
     {'name': 'heavy metal', 'url': 'https://www.last.fm/tag/heavy+metal'},
     {'name': 'favourite albums',
      'url': 'https://www.last.fm/tag/favourite+albums'}]},
   'wiki': {'published': '26 Nov 2008, 18:21',
    'summary': 'Ride The Lightning is the second album by thrash metal band Metallica. It was released on July 27, 1984 by Megaforce Records. It was re-released in the same year on November 19 by Elektra records. In the United States alone Ride The Lightning has sold over 5 million copies.\n\nRide the Lightning is often hailed by fans as a classic of the thrash metal genre and a vital bridge between the band\'s albums Kill \'Em All and Master of Puppets, pushing the <a href="http://www.last.fm/music/Metallica/Ride+the+Lightning">Read more on Last.fm</a>.',
    'content': 'Ride The Lightning is the second album by thrash metal band Metallica. It was released on July 27, 1984 by Megaforce Records. It was re-released in the same year on November 19 by Elektra records. In the United States alone Ride The Lightning has sold over 5 million copies.\n\nRide the Lightning is often hailed by fans as a classic of the thrash metal genre and a vital bridge between the band\'s albums Kill \'Em All and Master of Puppets, pushing the thrash metal of the debut into progressive territory more fully-realized on "Master of Puppets" and "...And Justice for All."\n\nRide the Lightning retains the speed of Kill \'Em All on songs like "Trapped Under Ice" and "Fight Fire with Fire", but also contains the first of Metallica\'s longer, more intricate tracks, such as "Fade to Black" and the nearly 9-minute closing instrumental "The Call of Ktulu". "Ride the Lightning" is the last Metallica album to credit Dave Mustaine.\n\nRide the Lightning was listed at #3 on a list compiled by metal-rules.com of the Top 100 Metal Albums of All Time and #5 by IGN Music on the Top 25 Metal Albums. <a href="http://www.last.fm/music/Metallica/Ride+the+Lightning">Read more on Last.fm</a>. User-contributed text is available under the Creative Commons By-SA License; additional terms may apply.'}}},
 {'album': {'name': 'Master of Puppets',
   'artist': 'Metallica',
   'mbid': 'b30c90dd-83f1-4897-ae36-58fb3935e5ee',
   'url': 'https://www.last.fm/music/Metallica/Master+of+Puppets',
   'image': [{'#text': 'https://lastfm-img2.akamaized.net/i/u/34s/07f492a00c904cc6ccf868010be4d5a6.png',
     'size': 'small'},
    {'#text': 'https://lastfm-img2.akamaized.net/i/u/64s/07f492a00c904cc6ccf868010be4d5a6.png',
     'size': 'medium'},
    {'#text': 'https://lastfm-img2.akamaized.net/i/u/174s/07f492a00c904cc6ccf868010be4d5a6.png',
     'size': 'large'},
    {'#text': 'https://lastfm-img2.akamaized.net/i/u/300x300/07f492a00c904cc6ccf868010be4d5a6.png',
     'size': 'extralarge'},
    {'#text': 'https://lastfm-img2.akamaized.net/i/u/07f492a00c904cc6ccf868010be4d5a6.png',
     'size': 'mega'},
    {'#text': 'https://lastfm-img2.akamaized.net/i/u/arQ/07f492a00c904cc6ccf868010be4d5a6.png',
     'size': ''}],
   'listeners': '869763',
   'playcount': '19695379',
   'tracks': {'track': [{'name': 'Battery',
      'url': 'https://www.last.fm/music/Metallica/_/Battery',
      'duration': '310',
      '@attr': {'rank': '1'},
      'streamable': {'#text': '0', 'playcount': '1259675'},
      'artist': {'name': 'Metallica',
       'mbid': '65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab',
       'url': 'https://www.last.fm/music/Metallica'}},
     {'name': 'Master of Puppets',
      'url': 'https://www.last.fm/music/Metallica/_/Master+of+Puppets',
      'duration': '516',
      '@attr': {'rank': '2'},
      'streamable': {'#text': '0', 'playcount': '972768'},
      'artist': {'name': 'Metallica',
       'mbid': '65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab',
       'url': 'https://www.last.fm/music/Metallica'}},
     {'name': 'The Thing That Should Not Be',
      'url': 'https://www.last.fm/music/Metallica/_/The+Thing+That+Should+Not+Be',
      'duration': '392',
      '@attr': {'rank': '3'},
      'streamable': {'#text': '0', 'playcount': '1257630'},
      'artist': {'name': 'Metallica',
       'mbid': '65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab',
       'url': 'https://www.last.fm/music/Metallica'}},
     {'name': 'Welcome Home (Sanitarium)',
      'url': 'https://www.last.fm/music/Metallica/_/Welcome+Home+(Sanitarium)',
      'duration': '388',
      '@attr': {'rank': '4'},
      'streamable': {'#text': '0', 'playcount': '820737'},
      'artist': {'name': 'Metallica',
       'mbid': '65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab',
       'url': 'https://www.last.fm/music/Metallica'}},
     {'name': 'Disposable Heroes',
      'url': 'https://www.last.fm/music/Metallica/_/Disposable+Heroes',
      'duration': '494',
      '@attr': {'rank': '5'},
      'streamable': {'#text': '0', 'playcount': '1574934'},
      'artist': {'name': 'Metallica',
       'mbid': '65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab',
       'url': 'https://www.last.fm/music/Metallica'}},
     {'name': 'Leper Messiah',
      'url': 'https://www.last.fm/music/Metallica/_/Leper+Messiah',
      'duration': '338',
      '@attr': {'rank': '6'},
      'streamable': {'#text': '0', 'playcount': '1934967'},
      'artist': {'name': 'Metallica',
       'mbid': '65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab',
       'url': 'https://www.last.fm/music/Metallica'}},
     {'name': 'Orion',
      'url': 'https://www.last.fm/music/Metallica/_/Orion',
      'duration': '492',
      '@attr': {'rank': '7'},
      'streamable': {'#text': '0', 'playcount': '1140333'},
      'artist': {'name': 'Metallica',
       'mbid': '65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab',
       'url': 'https://www.last.fm/music/Metallica'}},
     {'name': 'Damage, Inc.',
      'url': 'https://www.last.fm/music/Metallica/_/Damage,+Inc.',
      'duration': '308',
      '@attr': {'rank': '8'},
      'streamable': {'#text': '0', 'playcount': '1856042'},
      'artist': {'name': 'Metallica',
       'mbid': '65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab',
       'url': 'https://www.last.fm/music/Metallica'}}]},
   'tags': {'tag': [{'name': 'thrash metal',
      'url': 'https://www.last.fm/tag/thrash+metal'},
     {'name': 'albums I own', 'url': 'https://www.last.fm/tag/albums+I+own'},
     {'name': 'metal', 'url': 'https://www.last.fm/tag/metal'},
     {'name': 'heavy metal', 'url': 'https://www.last.fm/tag/heavy+metal'},
     {'name': 'favourite albums',
      'url': 'https://www.last.fm/tag/favourite+albums'}]},
   'wiki': {'published': '25 Jul 2008, 02:55',
    'summary': 'Master of Puppets is the third studio album by American heavy metal band Metallica. The album was recorded in 1985 and released by Elektra Records on March 3, 1986 in North America.\n\nNow widely considered a classic of thrash metal, the album proved to be a modest commercial success upon its release by reaching #29 on the U.S. Billboard 200, making it the very first thrash metal album to crack the Top 40. With the band\'s rising popularity from the release of Metallica <a href="http://www.last.fm/music/Metallica/Master+of+Puppets">Read more on Last.fm</a>.',

In [74]:
df_json_metalica = json_normalize(jsondata_metalica)
df_json_metalica

,album.name,album.artist,album.mbid,album.url,album.image,album.listeners,album.playcount,album.tracks.track,album.tags.tag,album.wiki.published,album.wiki.summary,album.wiki.content
0,Kill 'Em All,Metallica,c06ed440-f25d-3127-aadb-ebe9c685b3d8,https://www.last.fm/music/Metallica/Kill+%27Em...,[{'#text': 'https://lastfm-img2.akamaized.net/...,554430,13043742,"[{'name': 'Hit the Lights', 'url': 'https://ww...","[{'name': 'thrash metal', 'url': 'https://www....","01 Apr 2009, 22:18",Kill 'Em All is Metallica's first studio album...,Kill 'Em All is Metallica's first studio album...
1,Ride the Lightning,Metallica,2236dd07-a2f3-466a-973d-9069001a89da,https://www.last.fm/music/Metallica/Ride+the+L...,[{'#text': 'https://lastfm-img2.akamaized.net/...,761909,17549813,"[{'name': 'Fight Fire With Fire', 'url': 'http...","[{'name': 'thrash metal', 'url': 'https://www....","26 Nov 2008, 18:21",Ride The Lightning is the second album by thra...,Ride The Lightning is the second album by thra...
2,Master of Puppets,Metallica,b30c90dd-83f1-4897-ae36-58fb3935e5ee,https://www.last.fm/music/Metallica/Master+of+...,[{'#text': 'https://lastfm-img2.akamaized.net/...,869763,19695379,"[{'name': 'Battery', 'url': 'https://www.last....","[{'name': 'thrash metal', 'url': 'https://www....","25 Jul 2008, 02:55",Master of Puppets is the third studio album by...,Master of Puppets is the third studio album by...
3,And Justice For All,Metallica,NaN,https://www.last.fm/music/Metallica/And+Justic...,[{'#text': 'https://lastfm-img2.akamaized.net/...,141201,2880721,"[{'name': 'Blackened', 'url': 'https://www.las...","[{'name': 'thrash metal', 'url': 'https://www....","12 Jun 2012, 04:07",…And Justice for All is the fourth studio albu...,…And Justice for All is the fourth studio albu...

In [75]:
# Listar información: Listar el título del disco, y el contenido y fecha en el que se ha publicado en la wiki.
df_json_metalica_info = df_json_metalica[['album.name', 'album.wiki.published', 'album.wiki.content']]
df_json_metalica_info

,album.name,album.wiki.published,album.wiki.content
0,Kill 'Em All,"01 Apr 2009, 22:18",Kill 'Em All is Metallica's first studio album...
1,Ride the Lightning,"26 Nov 2008, 18:21",Ride The Lightning is the second album by thra...
2,Master of Puppets,"25 Jul 2008, 02:55",Master of Puppets is the third studio album by...
3,And Justice For All,"12 Jun 2012, 04:07",…And Justice for All is the fourth studio albu...

In [76]:
# Contar información: Mostrar los títulos de discos y el número de canciones que tiene cada una.
canciones_albumnes = []
for tracks in df_json_metalica['album.tracks.track']:
    canciones_albumnes.append(len(tracks))
canciones_albumnes

[10, 8, 8, 9]

In [77]:
df_json_metalica_info.loc[:,'num_canciones'] = canciones_albumnes
df_json_metalica_info

C:\Users\uie70742\AppData\Local\Temp\ipykernel_41600\2546553446.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_json_metalica_info.loc[:,'num_canciones'] = canciones_albumnes

,album.name,album.wiki.published,album.wiki.content,num_canciones
0,Kill 'Em All,"01 Apr 2009, 22:18",Kill 'Em All is Metallica's first studio album...,10
1,Ride the Lightning,"26 Nov 2008, 18:21",Ride The Lightning is the second album by thra...,8
2,Master of Puppets,"25 Jul 2008, 02:55",Master of Puppets is the third studio album by...,8
3,And Justice For All,"12 Jun 2012, 04:07",…And Justice for All is the fourth studio albu...,9

In [78]:
# Buscar o filtrar información: Recibe un límite inferior y otro superior, y muestra el título, y los nombres de las etiquetas ("tags") de los discos cuyos número de oyentes esté entre los dos límites.
df_json_metalica

,album.name,album.artist,album.mbid,album.url,album.image,album.listeners,album.playcount,album.tracks.track,album.tags.tag,album.wiki.published,album.wiki.summary,album.wiki.content
0,Kill 'Em All,Metallica,c06ed440-f25d-3127-aadb-ebe9c685b3d8,https://www.last.fm/music/Metallica/Kill+%27Em...,[{'#text': 'https://lastfm-img2.akamaized.net/...,554430,13043742,"[{'name': 'Hit the Lights', 'url': 'https://ww...","[{'name': 'thrash metal', 'url': 'https://www....","01 Apr 2009, 22:18",Kill 'Em All is Metallica's first studio album...,Kill 'Em All is Metallica's first studio album...
1,Ride the Lightning,Metallica,2236dd07-a2f3-466a-973d-9069001a89da,https://www.last.fm/music/Metallica/Ride+the+L...,[{'#text': 'https://lastfm-img2.akamaized.net/...,761909,17549813,"[{'name': 'Fight Fire With Fire', 'url': 'http...","[{'name': 'thrash metal', 'url': 'https://www....","26 Nov 2008, 18:21",Ride The Lightning is the second album by thra...,Ride The Lightning is the second album by thra...
2,Master of Puppets,Metallica,b30c90dd-83f1-4897-ae36-58fb3935e5ee,https://www.last.fm/music/Metallica/Master+of+...,[{'#text': 'https://lastfm-img2.akamaized.net/...,869763,19695379,"[{'name': 'Battery', 'url': 'https://www.last....","[{'name': 'thrash metal', 'url': 'https://www....","25 Jul 2008, 02:55",Master of Puppets is the third studio album by...,Master of Puppets is the third studio album by...
3,And Justice For All,Metallica,NaN,https://www.last.fm/music/Metallica/And+Justic...,[{'#text': 'https://lastfm-img2.akamaized.net/...,141201,2880721,"[{'name': 'Blackened', 'url': 'https://www.las...","[{'name': 'thrash metal', 'url': 'https://www....","12 Jun 2012, 04:07",…And Justice for All is the fourth studio albu...,…And Justice for All is the fourth studio albu...

In [79]:
lim_inferior = 1000
lim_superior = 500000

tags_tag = []
for tags in df_json_metalica['album.tags.tag']:
    list_tag = []
    for tg in tags:
        list_tag.append(tg['name'])
    tags_tag.append(list_tag)
tags_tag

[['thrash metal', 'albums I own', 'metal', 'heavy metal', 'speed metal'],
 ['thrash metal', 'albums I own', 'metal', 'heavy metal', 'favourite albums'],
 ['thrash metal', 'albums I own', 'metal', 'heavy metal', 'favourite albums'],
 ['thrash metal', 'heavy metal', 'metal', 'albums I own', 'metallica']]

In [80]:
df_json_metalica_info.loc[:,'tags_tag'] = tags_tag
df_json_metalica_info

C:\Users\uie70742\AppData\Local\Temp\ipykernel_41600\3561391734.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_json_metalica_info.loc[:,'tags_tag'] = tags_tag

,album.name,album.wiki.published,album.wiki.content,num_canciones,tags_tag
0,Kill 'Em All,"01 Apr 2009, 22:18",Kill 'Em All is Metallica's first studio album...,10,"[thrash metal, albums I own, metal, heavy meta..."
1,Ride the Lightning,"26 Nov 2008, 18:21",Ride The Lightning is the second album by thra...,8,"[thrash metal, albums I own, metal, heavy meta..."
2,Master of Puppets,"25 Jul 2008, 02:55",Master of Puppets is the third studio album by...,8,"[thrash metal, albums I own, metal, heavy meta..."
3,And Justice For All,"12 Jun 2012, 04:07",…And Justice for All is the fourth studio albu...,9,"[thrash metal, heavy metal, metal, albums I ow..."

In [81]:
lim_inferior, lim_superior

(1000, 500000)

In [82]:
df_json_metalica_info[(df_json_metalica['album.listeners'].astype(int)>= lim_inferior) & (df_json_metalica['album.listeners'].astype(int)<= lim_superior)]

,album.name,album.wiki.published,album.wiki.content,num_canciones,tags_tag
3,And Justice For All,"12 Jun 2012, 04:07",…And Justice for All is the fourth studio albu...,9,"[thrash metal, heavy metal, metal, albums I ow..."